- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - zsh
        - node
  tasks:
    - include: tasks/zsh.yml
    - name: Install asdf
      ansible.builtin.git:
        repo: "https://github.com/asdf-vm/asdf.git"
        dest: "~/.asdf"
        version: "v0.10.2"
      tags:
        - node
        - asdf
    - name: Update zshrc
      shell: echo '. $HOME/.asdf/asdf.sh' >> ~/.zshrc
      tags:
        - asdf
        - node
    - include: tasks/node.yml

