- hosts: localhost
  become: true
  vars:
    source_rsa_key: ".ssh/id_rsa"
    dest_rsa_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    source_ed25519_key: ".ssh/id_ed25519"
    dest_ed25519_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    asdf_bin: "{{ lookup('env', 'HOME') }}/.asdf/bin/asdf"
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - zsh
        - node
  tasks:
    - include: tasks/core-utilities.yml
    - include: tasks/docker.yml
    - include: tasks/ssh.yml
    - include: tasks/git-config.yml
    - include: tasks/zsh.yml
    - include: tasks/asdf.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    - include: tasks/ruby.yml
    - include: tasks/neovim.yml

