- name: Fetch dotfiles
  become_user: lucas
  ansible.builtin.git:
    repo: "git@github.com:lucashtm/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    accept_hostkey: yes
  tags:
    - dotfiles
- name: Install stow
  apt:
    name: "stow"
  tags:
    - dotfiles
- name: Stow zsh
  become_user: lucas
  shell: chdir=$HOME/.dotfiles stow zsh
  tags:
    - dotfiles
- name: Stow asdf
  become_user: lucas
  command: chdir=$HOME/.dotfiles stow asdf
  tags:
    - dotfiles
- name: Stow neovim
  become_user: lucas
  command: chdir=$HOME/.dotfiles stow nvim
  tags:
    - dotfiles
