- name: Ensure Work directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/Work/repos"
    owner: lucas
    group: lucas
    mode: 0700
    state: directory
  tags:
    - dotfiles
- name: Ensure Dev directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/Dev"
    owner: lucas
    group: lucas
    mode: 0700
    state: directory
  tags:
    - dotfiles
- name: Fetch dotfiles
  become_user: lucas
  ansible.builtin.git:
    repo: "git@github.com:lucashtm/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    accept_hostkey: yes
  tags:
    - dotfiles
- name: Install stow
  apt:
    name: "stow"
  tags:
    - dotfiles
- name: Stow zsh
  become_user: lucas
  shell: chdir=$HOME/.dotfiles stow zsh
  tags:
    - dotfiles
- name: Stow asdf
  become_user: lucas
  command: chdir=$HOME/.dotfiles stow asdf
  tags:
    - dotfiles
- name: Stow neovim
  become_user: lucas
  command: chdir=$HOME/.dotfiles stow nvim
  tags:
    - dotfiles
- name: Stow i3
  become_user: lucas
  command: chdir=$HOME/.dotfiles stow i3
  tags:
    - dotfiles
- name: Stow tmux
  become_user: lucas
  command: chdir=$HOME/.dotfiles stow tmux
  tags:
    - dotfiles
- name: Stow local bin scripts
  become_user: lucas
  command: chdir=$HOME/.dotfiles stow bin
  tags:
    - dotfiles
