- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - neovim
- name: Clone repo
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: ~/.neovim-source
    version: v0.8.2
  tags:
    - neovim
- name: Install neovim
  shell: chdir=~/.neovim-source make CMAKE_BUILD_TYPE=Release && make install
  tags:
    - neovim
