# - name: Install node asdf plugin
#   shell: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
#   tags:
#     - node
# - name: Install node 18
#   shell: asdf global nodejs 18.12.1
#   tags:
#     - node
