- name: Install ruby asdf plugin
  become: false
  shell: "{{ asdf_bin }} plugin add ruby https://github.com/asdf-vm/asdf-ruby.git"
  args:
    executable: /bin/zsh
  tags:
    - ruby
- name: Install ruby 2.7
  become: false
  shell: "{{ asdf_bin }} install ruby 2.7.6"
  args:
    executable: /bin/zsh
  tags:
    - ruby
- name: Sets ruby 2.7 as global
  become: false
  shell: "{{ asdf_bin }} global ruby 2.7.6"
  args:
    executable: /bin/zsh
  tags:
    - ruby
- name: Installs nokogiri (solargraph requirement)
  become: false
  shell: gem install nokogiri -v 1.15.5 
  args:
    executable: /bin/zsh
  tags:
    - ruby
- name: Installs solargraph
  become: false
  shell: gem install solargraph
  args:
    executable: /bin/zsh
  tags:
    - ruby
- name: Installs bundler
  become: false
  shell: gem install bundler:1.17.3
  args:
    executable: /bin/zsh
  tags:
    - ruby
