- name: Install ZSH
  apt: name=zsh
  tags:
    - zsh
- name: Change shell
  shell: chsh -s $(which zsh)
  tags:
    - zsh
- name: Ensure .zshrc doesnt exist
  file:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: absent
- name: Fetch prezto
  become_user: lucas
  ansible.builtin.git:
    repo: "git@github.com:sorin-ionescu/prezto.git"
    dest: "{{ lookup('env', 'HOME') }}/.zprezto"
    accept_hostkey: yes
